FROM golang:1.26-bookworm

RUN go install github.com/go-delve/delve/cmd/dlv@latest

WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .

EXPOSE 2345

ENTRYPOINT ["dlv", "debug", "./cmd/gogogot", "--headless", "--listen=:2345", "--api-version=2", "--accept-multiclient", "--continue"]
